version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: polla_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polla
    ports:
      - "5432:5432"
    volumes:
      - polla_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d polla"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: polla_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      # puedes overridear aqu√≠ si quieres
      APP_ENV: dev
      HTTP_ADDR: ":8080"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/polla?sslmode=disable"
      JWT_SECRET: "dev_jwt_secret_please_change"
      AES_KEY: "0123456789abcdef0123456789abcdef"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["go", "run", "./cmd/api"]

volumes:
  polla_pgdata:
